- name: Install Datadog Agent on servers in AWS
  hosts: tag_http_yes
  become: yes
  user: maintuser
  tasks:
    - name: Restart service httpd, in all cases
      service:
        name: httpd
        state: restarted
